---
- name: Ansible Find Example
  hosts: all
  vars:
    Files: []
  tasks:
   - name : Find files bigger than 100mb in size
     become: true
     find:
       paths: /var/log
       file_type: file
       patterns: 
#         - '^[a-z]*_[0-9]{8}\.log$'
#         - '^[a-z]*_[0-9]{8}\.log.gz$'
#         - '^_[0-9]{2,4}_.*.log$'
#         - '^[a-z]{1,5}_.*log$'
         - '^messages-[0-9]$'
       use_regex: yes
     register: output

   - debug: msg=" {{output.files}} "

#   - name: Delete the files matching
#     become: yes
#     file:
#       path: "{{item.path}}"
#       state: absent
#     with_items: "{{ output.files }}"
