---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:
    - name: Ensure that free space on the tested volume is greater than 15%
      assert:
        that:
          - mount.size_available > mount.size_total|float * 0.15
        msg: Disk space has reached 85% threshold
      vars:
        mount: "{{ ansible_mounts | selectattr('mount','equalto',item.mount) | list | first }}"
      with_items:
        - "{{ ansible_mounts }}"