---
- hosts: all
  become: yes 
  become_user: root
  become_method: sudo
  name: install openssh-clients
  tasks:
      - name: install openssh-clients
        yum:
          name: openssh-clients
          state: present
