---
- hosts: all
  serial: 3
  become: yes
  remote_user: apatsev
  tasks:
    - name: Run Puppet agent --test
      shell: "puppet agent --test"
      register: command_result
      failed_when: "'Error' in command_result.stderr"

    - name: Run Puppet agent --disable 'upgrade application'
      shell: "puppet agent --disable 'upgrade application'"
