---
- hosts: host_check_connection
  gather_facts: no
  tasks:

    - name: Include vars
      include_vars:
        file: conn_vars.yaml

    - name: check connectivity
      wait_for:
        host: "{{ item[0] }}"
        port: "{{ item[1] }}"
        state: started         # Port should be open
        delay: 0               # No wait before first check (sec)
        timeout: 3             # Stop checking after timeout (sec)
      loop: "{{ hosts }}"
      register: msgoutput

    - name: "Ansible | Print a msgoutput.stdout"
      debug:
        msg: "{{ msgoutput.stdout }}"
      when: msgoutput.stdout is defined

    - name: "Ansible | Print a msgoutput.stderr"
      debug:
        msg: "{{ msgoutput.stderr }}"
      when: msgoutput.stderr is defined
